name: update

on:
  workflow_dispatch:
    inputs:
      alan_version:
        description: 'Alan released version'
        required: true

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update formulae
        run: ./update_formulae.sh ${{ github.event.inputs.alan_version }}
      - name: Commit files
        uses: EndBug/add-and-commit@v7
        with:
          message: 'Bump version'
